In [19]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import sklearn.linear_model as lm
import matplotlib.pyplot as plt

In [20]:
df=pd.read_csv("Cat_human.csv")
df.head()

         Color Eye_color  Height  Legs Moustache Tail  Weight  label
0        black     black    5.14     2        No   No    70.0  human
1   dark_brown     brown    6.80     2        No   No    64.4  human
2  light_brown     brown    5.00     2       Yes   No    64.8  human
3  light_brown      blue    5.90     2        No   No    78.8  human
4  light_brown      blue    6.56     2        No   No    73.2  human

In [21]:
import sklearn.preprocessing as pre_process
import numpy as np
ordinal_encoding=pre_process.OrdinalEncoder()
#onehot_encoding=pre_process.OneHotEncoder()
standered_scalling=pre_process.StandardScaler()
#minmax_scalling=pre_process.MinMaxScaler()

In [22]:
from sklearn.compose import make_column_transformer
transform_x=make_column_transformer( (ordinal_encoding , ['Color','Eye_color','Moustache','Tail']),
(standered_scalling,['Height','Weight','Legs']))

In [25]:
X.head()

         Color Eye_color  Height  Legs Moustache Tail  Weight
0        black     black    5.14     2        No   No    70.0
1   dark_brown     brown    6.80     2        No   No    64.4
2  light_brown     brown    5.00     2       Yes   No    64.8
3  light_brown      blue    5.90     2        No   No    78.8
4  light_brown      blue    6.56     2        No   No    73.2

In [24]:
X=df.iloc[:,0:7]
Y=df.iloc[:,7]
Y
#Y.head(4)

0      human
1      human
2      human
3      human
4      human
       ...
195      Cat
196      Cat
197      Cat
198      Cat
199      Cat
Name: label, Length: 200, dtype: object

In [45]:
Y

0      human
1      human
2      human
3      human
4      human
       ...
195      Cat
196      Cat
197      Cat
198      Cat
199      Cat
Name: label, Length: 200, dtype: object

In [46]:
processed_x=transform_x.fit_transform(X)
processed_x

array([[ 0.        ,  0.        ,  0.        , ...,  0.64891286,
         1.30977483, -1.        ],
       [ 3.        ,  2.        ,  0.        , ...,  1.30274918,
         1.11669998, -1.        ],
       [ 5.        ,  2.        ,  1.        , ...,  0.59377003,
         1.13049104, -1.        ],
       ...,
       [ 6.        ,  0.        ,  1.        , ..., -1.16686151,
        -0.88422211,  1.        ],
       [ 1.        ,  4.        ,  1.        , ..., -0.96992286,
        -0.8764452 ,  1.        ],
       [ 2.        ,  1.        ,  1.        , ..., -1.04869832,
        -0.83237602,  1.        ]])

In [47]:
pd.DataFrame(processed_x)

       0    1    2    3         4         5    6
0    0.0  0.0  0.0  0.0  0.648913  1.309775 -1.0
1    3.0  2.0  0.0  0.0  1.302749  1.116700 -1.0
2    5.0  2.0  1.0  0.0  0.593770  1.130491 -1.0
3    5.0  1.0  0.0  0.0  0.948260  1.613178 -1.0
4    5.0  1.0  0.0  0.0  1.208219  1.420103 -1.0
..   ...  ...  ...  ...       ...       ...  ...
195  1.0  3.0  1.0  1.0 -0.926596 -1.024207  1.0
196  6.0  5.0  1.0  1.0 -0.828127 -0.907553  1.0
197  6.0  0.0  1.0  1.0 -1.166862 -0.884222  1.0
198  1.0  4.0  1.0  1.0 -0.969923 -0.876445  1.0
199  2.0  1.0  1.0  1.0 -1.048698 -0.832376  1.0

[200 rows x 7 columns]

In [48]:
Y

0      human
1      human
2      human
3      human
4      human
       ...
195      Cat
196      Cat
197      Cat
198      Cat
199      Cat
Name: label, Length: 200, dtype: object

In [28]:
np.c_[Y]

array([['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat']], dtype=object)

In [29]:
import numpy as np
ordinal_encoder=pre_process.OrdinalEncoder()
processed_y=ordinal_encoder.fit_transform(np.c_[Y])
processed_y

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [30]:
train_x,test_x,train_y,test_y=train_test_split(processed_x,processed_y)

In [31]:
model=lm.LogisticRegression()
model.fit(train_x,train_y)

C:\Users\Qc\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [32]:
import sklearn.tree as tr
import sklearn.metrics as sm
model=tr.ExtraTreeClassifier()
model.fit(train_x,train_y)

ExtraTreeClassifier()

In [33]:
pred_y=model.predict(test_x)
pred_y
pred_y=np.c_[pred_y]
pred_y
#pred_y=pred_y.reshape(-1,1)
#pred_y

array([[1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [34]:
pred_y_Class=ordinal_encoder.inverse_transform(pred_y)
pred_y_Class
test_y_Class=ordinal_encoder.inverse_transform(test_y)
test_y_Class
#test_y_Class=test_y_Class.reshape(1,-1)
#pred_y_Class=pred_y_Class.reshape(1,-1)
#pred_y_Class

array([['human'],
       ['human'],
       ['Cat'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['human'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['human'],
       ['Cat'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['Cat'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['human'],
       ['Cat'],
       ['human'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['human'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['human'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat']], dtype=object)

In [35]:
pd.DataFrame({"Test":test_y_Class[:,0],"pred":pred_y_Class[:,0]})

     Test   pred
0   human  human
1   human  human
2     Cat    Cat
3   human  human
4     Cat    Cat
5     Cat    Cat
6   human  human
7   human  human
8     Cat    Cat
9     Cat    Cat
10    Cat    Cat
11    Cat    Cat
12    Cat    Cat
13  human  human
14    Cat    Cat
15  human  human
16  human  human
17  human  human
18  human  human
19  human  human
20  human  human
21    Cat    Cat
22  human  human
23  human  human
24  human  human
25  human  human
26    Cat    Cat
27    Cat    Cat
28  human  human
29    Cat    Cat
30    Cat    Cat
31  human  human
32    Cat    Cat
33  human  human
34  human  human
35    Cat    Cat
36    Cat    Cat
37  human  human
38  human  human
39    Cat    Cat
40    Cat    Cat
41  human  human
42    Cat    Cat
43    Cat    Cat
44  human  human
45  human  human
46    Cat    Cat
47    Cat    Cat
48    Cat    Cat
49    Cat    Cat

In [36]:
test_y_Class[:,0]

array(['human', 'human', 'Cat', 'human', 'Cat', 'Cat', 'human', 'human',
       'Cat', 'Cat', 'Cat', 'Cat', 'Cat', 'human', 'Cat', 'human',
       'human', 'human', 'human', 'human', 'human', 'Cat', 'human',
       'human', 'human', 'human', 'Cat', 'Cat', 'human', 'Cat', 'Cat',
       'human', 'Cat', 'human', 'human', 'Cat', 'Cat', 'human', 'human',
       'Cat', 'Cat', 'human', 'Cat', 'Cat', 'human', 'human', 'Cat',
       'Cat', 'Cat', 'Cat'], dtype=object)

In [37]:
from sklearn import svm

In [49]:
svm_model = svm.SVC()

# Train the SVM classifier
svm_model.fit(train_x, train_y)

C:\Users\Qc\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC()

In [39]:
pred_y=svm_model.predict(test_x)
pred_y
pred_y=np.c_[pred_y]
pred_y

array([[1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [40]:
pred_y_Class=ordinal_encoder.inverse_transform(pred_y)
pred_y_Class
test_y_Class=ordinal_encoder.inverse_transform(test_y)
test_y_Class

array([['human'],
       ['human'],
       ['Cat'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['human'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['human'],
       ['Cat'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['Cat'],
       ['human'],
       ['human'],
       ['human'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['human'],
       ['Cat'],
       ['human'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['human'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['human'],
       ['human'],
       ['Cat'],
       ['Cat'],
       ['Cat'],
       ['Cat']], dtype=object)

In [41]:
pd.DataFrame({"Test":test_y_Class[:,0],"pred":pred_y_Class[:,0]})

     Test   pred
0   human  human
1   human  human
2     Cat    Cat
3   human  human
4     Cat    Cat
5     Cat    Cat
6   human  human
7   human  human
8     Cat    Cat
9     Cat    Cat
10    Cat    Cat
11    Cat    Cat
12    Cat    Cat
13  human  human
14    Cat    Cat
15  human  human
16  human  human
17  human  human
18  human  human
19  human  human
20  human  human
21    Cat    Cat
22  human  human
23  human  human
24  human  human
25  human  human
26    Cat    Cat
27    Cat    Cat
28  human  human
29    Cat    Cat
30    Cat    Cat
31  human  human
32    Cat    Cat
33  human  human
34  human  human
35    Cat    Cat
36    Cat    Cat
37  human  human
38  human  human
39    Cat    Cat
40    Cat    Cat
41  human  human
42    Cat    Cat
43    Cat    Cat
44  human  human
45  human  human
46    Cat    Cat
47    Cat    Cat
48    Cat    Cat
49    Cat    Cat

In [42]:
shuffled_df = df.sample(frac=1).reset_index(drop=True)

In [43]:
shuffled_df

           Color Eye_color  Height  Legs Moustache Tail     Weight  label
0           gray      blue    0.88     4       Yes  Yes   5.913534    Cat
1     dark_brown     black    6.14     2       Yes   No  40.800000  human
2          brown      gray    6.54     2        No   No  49.200000  human
3          white      gray    6.86     2        No   No  77.600000  human
4          black     black    1.16     4       Yes  Yes   1.853383    Cat
..           ...       ...     ...   ...       ...  ...        ...    ...
195        black     brown    5.24     2        No   No  43.200000  human
196        brown      gray    1.14     4       Yes  Yes   2.304511    Cat
197  light_brown      gray    6.18     2       Yes   No  42.000000  human
198   dark_brown     brown    6.06     2        No   No  60.800000  human
199        black      gray    1.18     4       Yes  Yes   2.680451    Cat

[200 rows x 8 columns]